// For WFC's Image Processor's multiple input feature

const IMAGES_GROUND = [
	MAP1_GROUND,
	//MAP2_GROUND,
	//MAP3_GROUND,
	//MAP4_GROUND
];

const IMAGES_STRUCTURES = [
	MAP1_STRUCTURES,
	MAP2_STRUCTURES,
	MAP3_STRUCTURES,
	//MAP4_STRUCTURES
];